# Generated by Django 2.2.3 on 2019-07-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='Dosya Adı')),
                ('xfile', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', verbose_name='Dokumanlarım')),
            ],
        ),
    ]
