# Generated by Django 2.2.3 on 2019-07-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='xfile',
            new_name='file',
        ),
    ]
