# Generated by Django 2.2.3 on 2019-07-24 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20190724_1941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportPost',
        ),
    ]
