# Generated by Django 2.2.3 on 2019-07-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefon No'),
        ),
    ]
