# Generated by Django 2.2.3 on 2019-07-23 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36, verbose_name='Döküman Başlık')),
                ('doc', models.FileField(upload_to='', verbose_name='Dosya')),
                ('type', models.CharField(max_length=36, verbose_name='Dosta Türü')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Dokuman Ekleme Tarihi')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documents_Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_hash', models.CharField(max_length=64, verbose_name='document_hash')),
            ],
        ),
        migrations.CreateModel(
            name='my_codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, verbose_name='Dokuman Turu')),
                ('code', models.CharField(max_length=16, verbose_name='Kısa Kodu')),
                ('title', models.CharField(max_length=32, verbose_name='Kod Açıklaması')),
            ],
        ),
        migrations.CreateModel(
            name='Documents_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Documents')),
            ],
        ),
    ]
