# Generated by Django 2.2.3 on 2019-07-23 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documents_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documents_hash',
            name='doc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Documents', verbose_name='document_id'),
        ),
    ]
