# Generated by Django 2.2.3 on 2019-07-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20190723_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Resim Dosyalarım'),
        ),
        migrations.AddField(
            model_name='documents',
            name='revision_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Revizyon Tarihi'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Dokuman Ekleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='doc',
            field=models.FileField(upload_to='', verbose_name='Dokumanlarım'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='type',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Dosta Türü'),
        ),
    ]
